export const TRACING_CONTEXT = 'TRACING_CONTEXT';
export const TRACING_EXTRACTOR_KEY = 'TRACING_EXTRACTOR';
export const DISABLE_TRACING_EXTRACTOR_KEY = 'DISABLE_TRACING_EXTRACTOR';
export const TRACING_REFERENCE_EXTRACTOR_KEY = 'TRACING_REFERENCE_EXTRACTOR';
export const TRACING_LOGGER_KEY = 'TRACING_LOGGER';
export const DISABLE_TRACING_LOGGER_KEY = 'DISABLE_TRACING_LOGGER';
